name: Build Image

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'
      tags:
        description: 'dispatch'  
  
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build Container Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./dockerfile
        platforms: linux/amd64
        push: true
        tags: possg/possg-fe:latest
    - 
      name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4        
      with:
          host: 52.79.198.243         
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          timeout: 40s  # 30초 기본        
          script: |
              docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
              docker pull possg/possg-fe:latest
              docker rm -f frontend-test
              docker run -d -p 80:80 --name frontend-test possg/possg-fe:latest
      